#include "telemetry.hpp"

#include <iostream>
#include <fstream>
#include <cstdio>
#include <cstring>

#include "config.hpp"
#include "sensors.hpp"

// ---------------------------------------------------------------------------
// State / Phase name helpers (used in CSV and console output)
// ---------------------------------------------------------------------------

static const char *stateName(State state)
{
    switch(state)
    {
        case BOOT:               return "BOOT";
        case TEST_MODE:          return "TEST_MODE";
        case Prelaunch_Check:    return "Prelaunch_Check";
        case Launch_Pad:         return "Launch_Pad";
        case Ascent:             return "Ascent";
        case Apogee_confirm:     return "Apogee_confirm";
        case Payload_Separation: return "Payload_Separation";
        case Descent:            return "Descent";
        case Landed:             return "Landed";
        case Beacon:             return "Beacon";
        default:                 return "UNKNOWN";
    }
}

static const char *flightPhaseName(FlightPhase phase)
{
    switch(phase)
    {
        case Flight_Grounded:          return "Grounded";
        case Flight_Powered_Ascent:    return "Powered ascent";
        case Flight_Coast:             return "Coast";
        case Flight_Ballistic_Descent: return "Ballistic descent";
        case Flight_Landed:            return "Landed";
        default:                       return "Unknown";
    }
}

// ---------------------------------------------------------------------------
// POINT 1: Hardware Transmission (LoRa via STM32 HAL UART)
// ---------------------------------------------------------------------------
// On the desktop simulation build, this function is a no-op stub.
// When ported to the STM32 + E22-900M22S (SX1262) module, replace the body
// with the actual HAL_UART_Transmit() call.
//
// The E22-900M22S is controlled over UART. To transmit a telemetry packet:
//   1. Make sure the module is in transparent transmission mode.
//   2. Call HAL_UART_Transmit(&huart2, (uint8_t*)csv_line, length, HAL_MAX_DELAY)
//      where &huart2 is whichever STM32 UART peripheral the module is wired to.
//
// STM32CubeIDE integration steps (for the future embedded build):
//   - Enable USART2 in CubeMX, set baud rate to match the LoRa module config.
//   - Include "usart.h" and call MX_USART2_UART_Init() in main before the loop.
//   - Replace the stub body below with the HAL call.
// ---------------------------------------------------------------------------
static void transmitOverLoRa(const char* csv_line, unsigned int length)
{
    // ----- DESKTOP BUILD: no hardware attached, nothing to transmit -----
    (void)csv_line;
    (void)length;

    // ----- STM32 EMBEDDED BUILD (uncomment when porting): -----
    //
    // #include "usart.h"   // generated by STM32CubeMX
    // HAL_UART_Transmit(&huart2,
    //                   (uint8_t*)csv_line,
    //                   (uint16_t)length,
    //                   HAL_MAX_DELAY);
}

// ---------------------------------------------------------------------------
// POINT 4: RF Command Receiver
// ---------------------------------------------------------------------------
// Checks whether the LoRa module has sent an uplink command from the ground
// station into our UART receive buffer and acts on it.
//
// Supported commands (ASCII, null-terminated):
//   "CMD_OFF" — ground station commands telemetry silence.
//   "CMD_ON"  — ground station re-enables telemetry.
//
// On desktop: simulates receiving no commands (always returns immediately).
// On STM32: replace the stub with HAL_UART_Receive() or use a DMA ring buffer.
// ---------------------------------------------------------------------------
void receiveRFCommands(RocketSystem &system)
{
    // ----- DESKTOP BUILD: no radio, no commands to receive -----
    // We simply zero out the command buffer every tick to show the
    // architecture is in place. The shouldSendTelemetry() guard below
    // will still respect the telemetry_muted flag if it were ever set.
    std::memset(system.last_rf_command, 0, sizeof(system.last_rf_command));

    // ----- STM32 EMBEDDED BUILD (uncomment when porting): -----
    //
    // uint8_t rx_buf[8] = {0};
    // if (HAL_UART_Receive(&huart2, rx_buf, sizeof(rx_buf), 10) == HAL_OK)
    // {
    //     std::memcpy(system.last_rf_command, rx_buf, sizeof(system.last_rf_command));
    //
    //     if (std::strncmp(system.last_rf_command, "CMD_OFF", 7) == 0)
    //     {
    //         system.telemetry_muted = true;
    //     }
    //     else if (std::strncmp(system.last_rf_command, "CMD_ON", 6) == 0)
    //     {
    //         system.telemetry_muted = false;
    //     }
    // }
}

// ---------------------------------------------------------------------------
// Rate gate — respects both the time interval AND the RF mute flag
// ---------------------------------------------------------------------------
bool shouldSendTelemetry(RocketSystem &system)
{
    // Respect the RF command mute flag (Point 4)
    if(system.telemetry_muted)
    {
        return false;
    }

    if(!system.flight_telemetry_enabled &&
       !system.recovery_beacon_enabled)
    {
        return false;
    }

    if(FlightConfig::TELEMETRY_INTERVAL_SECONDS <= 0.0f)
    {
        return true;
    }

    const float elapsed_since_last_packet =
        system.mission_elapsed_seconds -
        system.last_telemetry_time_seconds;

    return elapsed_since_last_packet >=
           FlightConfig::TELEMETRY_INTERVAL_SECONDS;
}

// ---------------------------------------------------------------------------
// Packet builder — transport-neutral snapshot of current system state
// ---------------------------------------------------------------------------
TelemetryPacket buildTelemetryPacket(RocketSystem &system)
{
    TelemetryPacket packet =
    {
        system.telemetry_sequence,
        system.mission_elapsed_seconds,
        system.current_state,
        system.current_flight_phase,
        readAltitude(system),
        system.vertical_velocity,
        system.vertical_acceleration,
        system.system_armed,
        system.fault_detected,
        system.descending,
        system.payload_deployed
    };

    return packet;
}

// ---------------------------------------------------------------------------
// Main telemetry send function
// Handles: CSV file write (Points 2 & 3) + LoRa radio transmission (Point 1)
// ---------------------------------------------------------------------------
void sendTelemetry(RocketSystem &system)
{
    TelemetryPacket packet = buildTelemetryPacket(system);

    // POINT 3: Competition-compliant filename: Flight_<TEAM_ID>.csv
    char filename[64];
    std::snprintf(filename, sizeof(filename),
                  "Flight_%s.csv", FlightConfig::TEAM_ID);

    std::ios_base::openmode mode = std::ios::app;
    if(packet.sequence == 0)
    {
        mode = std::ios::trunc; // overwrite at start of new mission
    }

    std::ofstream out(filename, mode);
    if(!out)
    {
        std::cerr << "[TELEMETRY] ERROR: Failed to open CSV file: "
                  << filename << "\n";
        return;
    }

    // Write CSV header on the very first packet
    if(packet.sequence == 0)
    {
        out << "TEAM ID,TIME STAMPING,PACKET COUNT,ALTITUDE,"
               "PRESSURE,TEMP,VOLTAGE,GNSS TIME,GNSS LATITUDE,"
               "GNSS LONGITUDE,GNSS ALTITUDE,GNSS SATS,"
               "ACCELEROMETER DATA,GYRO SPIN RATE,"
               "FLIGHT SOFTWARE STATE,ANY OPTIONAL DATA\n";
    }

    // POINT 2: All sensor fields now come from updateSensors() which
    //          computes realistic physics values each tick.
    //
    // Build the CSV row into a char buffer so we can also pass it
    // directly to transmitOverLoRa() without re-formatting.
    char csv_row[256];
    int len = std::snprintf(csv_row, sizeof(csv_row),
        "%s,%.2f,%u,%.2f,%.2f,%.1f,%.2f,%ld,%.6f,%.6f,%.2f,%d,%.3f,%.2f,%s,%s\n",
        FlightConfig::TEAM_ID,           // TEAM ID
        packet.mission_time_seconds,     // TIME STAMPING (s)
        packet.sequence,                 // PACKET COUNT
        packet.altitude,                 // ALTITUDE (m)
        system.pressure,                 // PRESSURE (Pa)  — real physics
        system.temperature,              // TEMP (°C)      — real physics
        system.voltage,                  // VOLTAGE (V)    — real physics
        system.gnss_time,                // GNSS TIME (s since epoch stub)
        system.gnss_latitude,            // GNSS LATITUDE
        system.gnss_longitude,           // GNSS LONGITUDE
        system.gnss_altitude,            // GNSS ALTITUDE (m)
        system.gnss_sats,                // GNSS SATS
        packet.vertical_acceleration,    // ACCELEROMETER DATA (m/s²)
        system.gyro_spin_rate,           // GYRO SPIN RATE (deg/s)
        stateName(packet.state),         // FLIGHT SOFTWARE STATE
        flightPhaseName(packet.flight_phase) // OPTIONAL DATA (flight phase)
    );

    // Write to the CSV file on disk
    out << csv_row;
    out.close();

    // POINT 1: Also transmit the same ASCII CSV row over the LoRa radio.
    // On desktop this is a no-op stub; on STM32 it calls HAL_UART_Transmit.
    if(len > 0)
    {
        transmitOverLoRa(csv_row, static_cast<unsigned int>(len));
    }

    system.telemetry_sequence++;
    system.last_telemetry_time_seconds = system.mission_elapsed_seconds;
}
